-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 21
-- Total Raw Fields: 127
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- AutoimmuneDiseases: Target heterogeneous autoimmune disease definitions tracked across development, aging, tissues, and disease stages.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS autoimmune_diseases (
  autoimmune_disease_id               TEXT                 PRIMARY KEY          -- Stable identifier for each autoimmune disease (e.g. sle, ra, t1d).
);
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS disease_label TEXT;                        -- Human-readable disease name.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS is_complex_disease BOOLEAN;                -- True when the disease is a multifactorial complex disease beyond simple monogenic traits.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS disease_stages TEXT;                       -- Disease stages for this autoimmune disease.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS treatments TEXT;                           -- Treatment histories for this disease.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS clinical_phenotypes TEXT;                  -- Clinical phenotypes observed for this disease.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS individual_predictions TEXT;               -- Predictions of disease onset, severity, and treatment response.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS counterfactual_trajectories TEXT;          -- Counterfactual disease trajectories for this disease.
ALTER TABLE autoimmune_diseases ADD COLUMN IF NOT EXISTS intervention_targets TEXT;                 -- Experimentally falsifiable intervention targets.
COMMENT ON TABLE autoimmune_diseases IS 'Target heterogeneous autoimmune disease definitions tracked across development, aging, tissues, and disease stages.';
COMMENT ON COLUMN autoimmune_diseases.autoimmune_disease_id IS 'Stable identifier for each autoimmune disease (e.g. sle, ra, t1d).';
COMMENT ON COLUMN autoimmune_diseases.disease_label IS 'Human-readable disease name.';
COMMENT ON COLUMN autoimmune_diseases.is_complex_disease IS 'True when the disease is a multifactorial complex disease beyond simple monogenic traits.';
COMMENT ON COLUMN autoimmune_diseases.disease_stages IS 'Disease stages for this autoimmune disease.';
COMMENT ON COLUMN autoimmune_diseases.treatments IS 'Treatment histories for this disease.';
COMMENT ON COLUMN autoimmune_diseases.clinical_phenotypes IS 'Clinical phenotypes observed for this disease.';
COMMENT ON COLUMN autoimmune_diseases.individual_predictions IS 'Predictions of disease onset, severity, and treatment response.';
COMMENT ON COLUMN autoimmune_diseases.counterfactual_trajectories IS 'Counterfactual disease trajectories for this disease.';
COMMENT ON COLUMN autoimmune_diseases.intervention_targets IS 'Experimentally falsifiable intervention targets.';

-- ----------------------------------------------------------------------------
-- DiseaseStages: Ordered disease stages capturing presymptomatic, active, remission, and treatment-refractory phases along disease progression.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS disease_stages (
  disease_stage_id                    TEXT                 PRIMARY KEY          -- Stable identifier for each disease stage.
);
ALTER TABLE disease_stages ADD COLUMN IF NOT EXISTS stage_label TEXT;                               -- Human-readable stage label (e.g. presymptomatic, active).
ALTER TABLE disease_stages ADD COLUMN IF NOT EXISTS sort_order INTEGER;                             -- Numeric ordering of stages along disease progression.
ALTER TABLE disease_stages ADD COLUMN IF NOT EXISTS autoimmune_disease TEXT;                        -- Parent autoimmune disease.
COMMENT ON TABLE disease_stages IS 'Ordered disease stages capturing presymptomatic, active, remission, and treatment-refractory phases along disease progression.';
COMMENT ON COLUMN disease_stages.disease_stage_id IS 'Stable identifier for each disease stage.';
COMMENT ON COLUMN disease_stages.stage_label IS 'Human-readable stage label (e.g. presymptomatic, active).';
COMMENT ON COLUMN disease_stages.sort_order IS 'Numeric ordering of stages along disease progression.';
COMMENT ON COLUMN disease_stages.autoimmune_disease IS 'Parent autoimmune disease.';

-- ----------------------------------------------------------------------------
-- Tissues: Anatomical tissues where omics assays resolve cell-state-specific effects; includes cases of missing tissues.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tissues (
  tissue_id                           TEXT                 PRIMARY KEY          -- Stable identifier for each tissue type.
);
ALTER TABLE tissues ADD COLUMN IF NOT EXISTS tissue_label TEXT;                                     -- Human-readable tissue name (blood, gut, synovium, skin, brain).
ALTER TABLE tissues ADD COLUMN IF NOT EXISTS omics_assays TEXT;                                     -- Omics assays performed on this tissue.
COMMENT ON TABLE tissues IS 'Anatomical tissues where omics assays resolve cell-state-specific effects; includes cases of missing tissues.';
COMMENT ON COLUMN tissues.tissue_id IS 'Stable identifier for each tissue type.';
COMMENT ON COLUMN tissues.tissue_label IS 'Human-readable tissue name (blood, gut, synovium, skin, brain).';
COMMENT ON COLUMN tissues.omics_assays IS 'Omics assays performed on this tissue.';

-- ----------------------------------------------------------------------------
-- OmicsModalities: Registry of omics assay modalities: RNA-seq, ATAC-seq, proteomics, metabolomics, methylomes, chromatin-conformation, immune-receptor repertoires, microbiomes, and long-read genomes.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS omics_modalities (
  omics_modality_id                   TEXT                 PRIMARY KEY          -- Stable identifier for each omics modality.
);
ALTER TABLE omics_modalities ADD COLUMN IF NOT EXISTS modality_label TEXT;                          -- Human-readable modality name.
ALTER TABLE omics_modalities ADD COLUMN IF NOT EXISTS is_single_cell BOOLEAN;                       -- True for single-cell or spatial assays resolving cellular states.
ALTER TABLE omics_modalities ADD COLUMN IF NOT EXISTS omics_assays TEXT;                            -- Assays of this modality.
COMMENT ON TABLE omics_modalities IS 'Registry of omics assay modalities: RNA-seq, ATAC-seq, proteomics, metabolomics, methylomes, chromatin-conformation, immune-receptor repertoires, microbiomes, and long-read genomes.';
COMMENT ON COLUMN omics_modalities.omics_modality_id IS 'Stable identifier for each omics modality.';
COMMENT ON COLUMN omics_modalities.modality_label IS 'Human-readable modality name.';
COMMENT ON COLUMN omics_modalities.is_single_cell IS 'True for single-cell or spatial assays resolving cellular states.';
COMMENT ON COLUMN omics_modalities.omics_assays IS 'Assays of this modality.';

-- ----------------------------------------------------------------------------
-- FederatedDatasets: Privacy-preserving federated datasets contributing cohort partitions without centralizing raw genomes.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS federated_datasets (
  federated_dataset_id                TEXT                 PRIMARY KEY          -- Stable identifier for each federated data node.
);
ALTER TABLE federated_datasets ADD COLUMN IF NOT EXISTS node_label TEXT;                            -- Human-readable federated node name.
ALTER TABLE federated_datasets ADD COLUMN IF NOT EXISTS region TEXT;                                -- Geographic region; shifting environments may alter exposure profiles.
ALTER TABLE federated_datasets ADD COLUMN IF NOT EXISTS is_privacy_preserving BOOLEAN;              -- True when node uses privacy-preserving federated learning.
ALTER TABLE federated_datasets ADD COLUMN IF NOT EXISTS individuals TEXT;                           -- Individuals linked to this federated dataset.
ALTER TABLE federated_datasets ADD COLUMN IF NOT EXISTS omics_assays TEXT;                          -- Omics assays sourced from this node.
ALTER TABLE federated_datasets ADD COLUMN IF NOT EXISTS cohort_replications TEXT;                   -- Replications run in this cohort node.
COMMENT ON TABLE federated_datasets IS 'Privacy-preserving federated datasets contributing cohort partitions without centralizing raw genomes.';
COMMENT ON COLUMN federated_datasets.federated_dataset_id IS 'Stable identifier for each federated data node.';
COMMENT ON COLUMN federated_datasets.node_label IS 'Human-readable federated node name.';
COMMENT ON COLUMN federated_datasets.region IS 'Geographic region; shifting environments may alter exposure profiles.';
COMMENT ON COLUMN federated_datasets.is_privacy_preserving IS 'True when node uses privacy-preserving federated learning.';
COMMENT ON COLUMN federated_datasets.individuals IS 'Individuals linked to this federated dataset.';
COMMENT ON COLUMN federated_datasets.omics_assays IS 'Omics assays sourced from this node.';
COMMENT ON COLUMN federated_datasets.cohort_replications IS 'Replications run in this cohort node.';

-- ----------------------------------------------------------------------------
-- VariantTypes: Classification of genomic variant mechanisms: regulatory, coding, repeat expansions, mobile-element insertions, HLA haplotypes, structural variants, de novo mutations, somatic mosaicism, mitochondrial variation.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS variant_types (
  variant_type_id                     TEXT                 PRIMARY KEY          -- Stable identifier for each variant type.
);
ALTER TABLE variant_types ADD COLUMN IF NOT EXISTS type_label TEXT;                                 -- Human-readable variant mechanism label.
ALTER TABLE variant_types ADD COLUMN IF NOT EXISTS is_rare_variant_class BOOLEAN;                   -- True when this type contributes to rare-variant burden scoring.
ALTER TABLE variant_types ADD COLUMN IF NOT EXISTS genomic_variants TEXT;                           -- Genomic variants of this type.
COMMENT ON TABLE variant_types IS 'Classification of genomic variant mechanisms: regulatory, coding, repeat expansions, mobile-element insertions, HLA haplotypes, structural variants, de novo mutations, somatic mosaicism, mitochondrial variation.';
COMMENT ON COLUMN variant_types.variant_type_id IS 'Stable identifier for each variant type.';
COMMENT ON COLUMN variant_types.type_label IS 'Human-readable variant mechanism label.';
COMMENT ON COLUMN variant_types.is_rare_variant_class IS 'True when this type contributes to rare-variant burden scoring.';
COMMENT ON COLUMN variant_types.genomic_variants IS 'Genomic variants of this type.';

-- ----------------------------------------------------------------------------
-- Individuals: Ancestrally diverse cohort participants whose phased genomes, omics profiles, exposures, and clinical phenotypes feed causal architecture inference.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS individuals (
  individual_id                       TEXT                 PRIMARY KEY          -- Stable identifier for each individual in the million-person cohort.
);
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS given_name TEXT;                                   -- Participant given name (de-identified mock).
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS family_name TEXT;                                  -- Participant family name (de-identified mock).
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS ancestry_label TEXT;                               -- Ancestry label for population stratification and ancestry-equitable risk prediction.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS age_years INTEGER;                                 -- Age in years spanning development and aging windows.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS is_ancestry_absent_from_training BOOLEAN;          -- True when individual ancestry was absent from primary training data.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS federated_dataset TEXT;                            -- Federated dataset node when enrolled via privacy-preserving federation.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS enrollment_date TIMESTAMPTZ;                       -- Longitudinal cohort enrollment date.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS has_cryptic_relatedness_flag BOOLEAN;              -- True when cryptic relatedness or assortative mating bias detected.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS genomic_variants TEXT;                             -- Genomic variants for this individual.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS omics_assays TEXT;                                 -- Omics assays for this individual.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS environmental_exposures TEXT;                      -- Longitudinal environmental exposures.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS treatments TEXT;                                   -- Treatment histories.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS clinical_phenotypes TEXT;                          -- Clinical phenotypes.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS causal_mechanisms TEXT;                            -- Inferred causal mechanisms.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS epistatic_interactions TEXT;                       -- Epistatic interactions.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS counterfactual_trajectories TEXT;                  -- Counterfactual trajectories.
ALTER TABLE individuals ADD COLUMN IF NOT EXISTS individual_predictions TEXT;                       -- Individual predictions.
COMMENT ON TABLE individuals IS 'Ancestrally diverse cohort participants whose phased genomes, omics profiles, exposures, and clinical phenotypes feed causal architecture inference.';
COMMENT ON COLUMN individuals.individual_id IS 'Stable identifier for each individual in the million-person cohort.';
COMMENT ON COLUMN individuals.given_name IS 'Participant given name (de-identified mock).';
COMMENT ON COLUMN individuals.family_name IS 'Participant family name (de-identified mock).';
COMMENT ON COLUMN individuals.ancestry_label IS 'Ancestry label for population stratification and ancestry-equitable risk prediction.';
COMMENT ON COLUMN individuals.age_years IS 'Age in years spanning development and aging windows.';
COMMENT ON COLUMN individuals.is_ancestry_absent_from_training IS 'True when individual ancestry was absent from primary training data.';
COMMENT ON COLUMN individuals.federated_dataset IS 'Federated dataset node when enrolled via privacy-preserving federation.';
COMMENT ON COLUMN individuals.enrollment_date IS 'Longitudinal cohort enrollment date.';
COMMENT ON COLUMN individuals.has_cryptic_relatedness_flag IS 'True when cryptic relatedness or assortative mating bias detected.';
COMMENT ON COLUMN individuals.genomic_variants IS 'Genomic variants for this individual.';
COMMENT ON COLUMN individuals.omics_assays IS 'Omics assays for this individual.';
COMMENT ON COLUMN individuals.environmental_exposures IS 'Longitudinal environmental exposures.';
COMMENT ON COLUMN individuals.treatments IS 'Treatment histories.';
COMMENT ON COLUMN individuals.clinical_phenotypes IS 'Clinical phenotypes.';
COMMENT ON COLUMN individuals.causal_mechanisms IS 'Inferred causal mechanisms.';
COMMENT ON COLUMN individuals.epistatic_interactions IS 'Epistatic interactions.';
COMMENT ON COLUMN individuals.counterfactual_trajectories IS 'Counterfactual trajectories.';
COMMENT ON COLUMN individuals.individual_predictions IS 'Individual predictions.';

-- ----------------------------------------------------------------------------
-- GenomicVariants: Genomic variant calls per individual spanning regulatory, coding, structural, HLA haplotypes, de novo mutations, somatic mosaicism, and mitochondrial variation.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS genomic_variants (
  genomic_variant_id                  TEXT                 PRIMARY KEY          -- Stable identifier for each genomic variant record.
);
ALTER TABLE genomic_variants ADD COLUMN IF NOT EXISTS variant_label TEXT;                           -- Human-readable variant label (gene/locus).
ALTER TABLE genomic_variants ADD COLUMN IF NOT EXISTS individual TEXT;                              -- Individual carrying this variant.
ALTER TABLE genomic_variants ADD COLUMN IF NOT EXISTS variant_type TEXT;                            -- Variant mechanism classification.
ALTER TABLE genomic_variants ADD COLUMN IF NOT EXISTS allele_frequency NUMERIC;                     -- Population allele frequency for rare-variant burden.
ALTER TABLE genomic_variants ADD COLUMN IF NOT EXISTS has_allele_specific_expression BOOLEAN;       -- True when allele-specific expression observed.
COMMENT ON TABLE genomic_variants IS 'Genomic variant calls per individual spanning regulatory, coding, structural, HLA haplotypes, de novo mutations, somatic mosaicism, and mitochondrial variation.';
COMMENT ON COLUMN genomic_variants.genomic_variant_id IS 'Stable identifier for each genomic variant record.';
COMMENT ON COLUMN genomic_variants.variant_label IS 'Human-readable variant label (gene/locus).';
COMMENT ON COLUMN genomic_variants.individual IS 'Individual carrying this variant.';
COMMENT ON COLUMN genomic_variants.variant_type IS 'Variant mechanism classification.';
COMMENT ON COLUMN genomic_variants.allele_frequency IS 'Population allele frequency for rare-variant burden.';
COMMENT ON COLUMN genomic_variants.has_allele_specific_expression IS 'True when allele-specific expression observed.';

-- ----------------------------------------------------------------------------
-- OmicsAssays: Omics assay instances linking individuals to modalities and tissues; captures batch effects, measurement error, and missing tissues.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS omics_assays (
  omics_assay_id                      TEXT                 PRIMARY KEY          -- Stable identifier for each omics assay.
);
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS assay_label TEXT;                                 -- Human-readable assay label.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS individual TEXT;                                  -- Individual assayed.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS omics_modality TEXT;                              -- Omics modality used.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS tissue TEXT;                                      -- Tissue sampled; empty when missing tissues.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS federated_dataset TEXT;                           -- Source federated node if applicable.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS batch_id TEXT;                                    -- Sequencing batch for batch effects control.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS measurement_error_score NUMERIC;                  -- Estimated measurement error (0-1).
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS has_cell_state_specific_effect BOOLEAN;           -- True when cell-state-specific effects detected.
ALTER TABLE omics_assays ADD COLUMN IF NOT EXISTS evidence_items TEXT;                              -- Evidence items measured in this assay.
COMMENT ON TABLE omics_assays IS 'Omics assay instances linking individuals to modalities and tissues; captures batch effects, measurement error, and missing tissues.';
COMMENT ON COLUMN omics_assays.omics_assay_id IS 'Stable identifier for each omics assay.';
COMMENT ON COLUMN omics_assays.assay_label IS 'Human-readable assay label.';
COMMENT ON COLUMN omics_assays.individual IS 'Individual assayed.';
COMMENT ON COLUMN omics_assays.omics_modality IS 'Omics modality used.';
COMMENT ON COLUMN omics_assays.tissue IS 'Tissue sampled; empty when missing tissues.';
COMMENT ON COLUMN omics_assays.federated_dataset IS 'Source federated node if applicable.';
COMMENT ON COLUMN omics_assays.batch_id IS 'Sequencing batch for batch effects control.';
COMMENT ON COLUMN omics_assays.measurement_error_score IS 'Estimated measurement error (0-1).';
COMMENT ON COLUMN omics_assays.has_cell_state_specific_effect IS 'True when cell-state-specific effects detected.';
COMMENT ON COLUMN omics_assays.evidence_items IS 'Evidence items measured in this assay.';

-- ----------------------------------------------------------------------------
-- EvidenceItems: One observed support signal for a causal mechanism, measured by one omics assay. Mechanism confidence is an aggregation over these rows.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS evidence_items (
  evidence_item_id                    TEXT                 PRIMARY KEY          -- Stable id for this evidence observation.
);
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS evidence_label TEXT;                            -- Human label for the evidence row.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS causal_mechanism TEXT;                          -- FK to the mechanism this evidence supports.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS omics_assay TEXT;                               -- FK to the omics assay this signal was measured in.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS effect_size NUMERIC;                            -- OBSERVATION: measured (absolute) effect magnitude.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS standard_error NUMERIC;                         -- OBSERVATION: measured standard error of the effect.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS is_cross_modality BOOLEAN;                      -- OBSERVATION: TRUE if this signal comes from a different omics modality than the mechanism's primary one.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS is_negative_control_arm BOOLEAN;                -- OBSERVATION: TRUE if this row is a measured control arm rather than support.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS is_adjusted_for_ancestry_pcs BOOLEAN;           -- OBSERVATION: TRUE if the analysis adjusted for ancestry principal components.
ALTER TABLE evidence_items ADD COLUMN IF NOT EXISTS is_adjusted_for_batch BOOLEAN;                  -- OBSERVATION: TRUE if the analysis adjusted for batch.
COMMENT ON TABLE evidence_items IS 'One observed support signal for a causal mechanism, measured by one omics assay. Mechanism confidence is an aggregation over these rows.';
COMMENT ON COLUMN evidence_items.evidence_item_id IS 'Stable id for this evidence observation.';
COMMENT ON COLUMN evidence_items.evidence_label IS 'Human label for the evidence row.';
COMMENT ON COLUMN evidence_items.causal_mechanism IS 'FK to the mechanism this evidence supports.';
COMMENT ON COLUMN evidence_items.omics_assay IS 'FK to the omics assay this signal was measured in.';
COMMENT ON COLUMN evidence_items.effect_size IS 'OBSERVATION: measured (absolute) effect magnitude.';
COMMENT ON COLUMN evidence_items.standard_error IS 'OBSERVATION: measured standard error of the effect.';
COMMENT ON COLUMN evidence_items.is_cross_modality IS 'OBSERVATION: TRUE if this signal comes from a different omics modality than the mechanism''s primary one.';
COMMENT ON COLUMN evidence_items.is_negative_control_arm IS 'OBSERVATION: TRUE if this row is a measured control arm rather than support.';
COMMENT ON COLUMN evidence_items.is_adjusted_for_ancestry_pcs IS 'OBSERVATION: TRUE if the analysis adjusted for ancestry principal components.';
COMMENT ON COLUMN evidence_items.is_adjusted_for_batch IS 'OBSERVATION: TRUE if the analysis adjusted for batch.';

-- ----------------------------------------------------------------------------
-- CohortReplications: One re-test of a causal mechanism in another federated cohort. Replication and cross-ancestry transport are aggregations over these rows.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cohort_replications (
  cohort_replication_id               TEXT                 PRIMARY KEY          -- Stable id for this replication attempt.
);
ALTER TABLE cohort_replications ADD COLUMN IF NOT EXISTS replication_label TEXT;                    -- Human label.
ALTER TABLE cohort_replications ADD COLUMN IF NOT EXISTS causal_mechanism TEXT;                     -- FK to the mechanism being re-tested.
ALTER TABLE cohort_replications ADD COLUMN IF NOT EXISTS federated_dataset TEXT;                    -- FK to the cohort node the re-test ran in.
ALTER TABLE cohort_replications ADD COLUMN IF NOT EXISTS replication_effect_sign INTEGER;           -- OBSERVATION: sign of the re-estimated effect (+1 / -1 / 0).
ALTER TABLE cohort_replications ADD COLUMN IF NOT EXISTS replication_p_value NUMERIC;               -- OBSERVATION: p-value of the re-test.
ALTER TABLE cohort_replications ADD COLUMN IF NOT EXISTS replication_ancestry_label TEXT;           -- OBSERVATION: ancestry of the cohort the re-test ran in.
COMMENT ON TABLE cohort_replications IS 'One re-test of a causal mechanism in another federated cohort. Replication and cross-ancestry transport are aggregations over these rows.';
COMMENT ON COLUMN cohort_replications.cohort_replication_id IS 'Stable id for this replication attempt.';
COMMENT ON COLUMN cohort_replications.replication_label IS 'Human label.';
COMMENT ON COLUMN cohort_replications.causal_mechanism IS 'FK to the mechanism being re-tested.';
COMMENT ON COLUMN cohort_replications.federated_dataset IS 'FK to the cohort node the re-test ran in.';
COMMENT ON COLUMN cohort_replications.replication_effect_sign IS 'OBSERVATION: sign of the re-estimated effect (+1 / -1 / 0).';
COMMENT ON COLUMN cohort_replications.replication_p_value IS 'OBSERVATION: p-value of the re-test.';
COMMENT ON COLUMN cohort_replications.replication_ancestry_label IS 'OBSERVATION: ancestry of the cohort the re-test ran in.';

-- ----------------------------------------------------------------------------
-- NegativeControlTests: One stratification / permutation control on a causal mechanism. A true causal signal collapses under the control.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS negative_control_tests (
  negative_control_test_id            TEXT                 PRIMARY KEY          -- Stable id for this control test.
);
ALTER TABLE negative_control_tests ADD COLUMN IF NOT EXISTS control_label TEXT;                     -- Human label.
ALTER TABLE negative_control_tests ADD COLUMN IF NOT EXISTS causal_mechanism TEXT;                  -- FK to the mechanism being controlled.
ALTER TABLE negative_control_tests ADD COLUMN IF NOT EXISTS test_kind TEXT;                         -- OBSERVATION: kind of control (ancestry-permutation / batch-stratified / negative-control).
ALTER TABLE negative_control_tests ADD COLUMN IF NOT EXISTS permutation_effect_size NUMERIC;        -- OBSERVATION: (absolute) effect measured under the null/permuted control.
ALTER TABLE negative_control_tests ADD COLUMN IF NOT EXISTS null_threshold NUMERIC;                 -- OBSERVATION: pre-registered null-band half-width the control must stay within.
COMMENT ON TABLE negative_control_tests IS 'One stratification / permutation control on a causal mechanism. A true causal signal collapses under the control.';
COMMENT ON COLUMN negative_control_tests.negative_control_test_id IS 'Stable id for this control test.';
COMMENT ON COLUMN negative_control_tests.control_label IS 'Human label.';
COMMENT ON COLUMN negative_control_tests.causal_mechanism IS 'FK to the mechanism being controlled.';
COMMENT ON COLUMN negative_control_tests.test_kind IS 'OBSERVATION: kind of control (ancestry-permutation / batch-stratified / negative-control).';
COMMENT ON COLUMN negative_control_tests.permutation_effect_size IS 'OBSERVATION: (absolute) effect measured under the null/permuted control.';
COMMENT ON COLUMN negative_control_tests.null_threshold IS 'OBSERVATION: pre-registered null-band half-width the control must stay within.';

-- ----------------------------------------------------------------------------
-- EnvironmentalExposures: Longitudinal environmental exposures contributing to gene-environment-microbiome interactions and shifting environments.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS environmental_exposures (
  environmental_exposure_id           TEXT                 PRIMARY KEY          -- Stable identifier for each exposure record.
);
ALTER TABLE environmental_exposures ADD COLUMN IF NOT EXISTS exposure_label TEXT;                   -- Exposure name (smoking, UV, particulate, etc.).
ALTER TABLE environmental_exposures ADD COLUMN IF NOT EXISTS individual TEXT;                       -- Exposed individual.
ALTER TABLE environmental_exposures ADD COLUMN IF NOT EXISTS exposure_level NUMERIC;                -- Quantified exposure intensity.
ALTER TABLE environmental_exposures ADD COLUMN IF NOT EXISTS exposure_start_date TIMESTAMPTZ;       -- Start of longitudinal exposure window.
ALTER TABLE environmental_exposures ADD COLUMN IF NOT EXISTS is_maternal_effect BOOLEAN;            -- True when exposure reflects maternal developmental effects.
COMMENT ON TABLE environmental_exposures IS 'Longitudinal environmental exposures contributing to gene-environment-microbiome interactions and shifting environments.';
COMMENT ON COLUMN environmental_exposures.environmental_exposure_id IS 'Stable identifier for each exposure record.';
COMMENT ON COLUMN environmental_exposures.exposure_label IS 'Exposure name (smoking, UV, particulate, etc.).';
COMMENT ON COLUMN environmental_exposures.individual IS 'Exposed individual.';
COMMENT ON COLUMN environmental_exposures.exposure_level IS 'Quantified exposure intensity.';
COMMENT ON COLUMN environmental_exposures.exposure_start_date IS 'Start of longitudinal exposure window.';
COMMENT ON COLUMN environmental_exposures.is_maternal_effect IS 'True when exposure reflects maternal developmental effects.';

-- ----------------------------------------------------------------------------
-- Treatments: Treatment histories capturing treatment-induced changes, treatment response, and adverse effects.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS treatments (
  treatment_id                        TEXT                 PRIMARY KEY          -- Stable identifier for each treatment record.
);
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS treatment_label TEXT;                               -- Therapy name.
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS individual TEXT;                                    -- Treated individual.
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS autoimmune_disease TEXT;                            -- Target autoimmune disease.
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS treatment_response TEXT;                            -- Response category: Complete, Partial, None, Adverse.
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS has_treatment_induced_change BOOLEAN;               -- True when molecular state shifted due to therapy.
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS has_adverse_effect BOOLEAN;                         -- True when adverse effects observed.
ALTER TABLE treatments ADD COLUMN IF NOT EXISTS start_date TIMESTAMPTZ;                             -- Treatment start date.
COMMENT ON TABLE treatments IS 'Treatment histories capturing treatment-induced changes, treatment response, and adverse effects.';
COMMENT ON COLUMN treatments.treatment_id IS 'Stable identifier for each treatment record.';
COMMENT ON COLUMN treatments.treatment_label IS 'Therapy name.';
COMMENT ON COLUMN treatments.individual IS 'Treated individual.';
COMMENT ON COLUMN treatments.autoimmune_disease IS 'Target autoimmune disease.';
COMMENT ON COLUMN treatments.treatment_response IS 'Response category: Complete, Partial, None, Adverse.';
COMMENT ON COLUMN treatments.has_treatment_induced_change IS 'True when molecular state shifted due to therapy.';
COMMENT ON COLUMN treatments.has_adverse_effect IS 'True when adverse effects observed.';
COMMENT ON COLUMN treatments.start_date IS 'Treatment start date.';

-- ----------------------------------------------------------------------------
-- ClinicalPhenotypes: Clinical phenotypes including severity, immune dysfunction markers, and feedback from disease progression.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical_phenotypes (
  clinical_phenotype_id               TEXT                 PRIMARY KEY          -- Stable identifier for each phenotype measurement.
);
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS phenotype_label TEXT;                      -- Phenotype name.
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS individual TEXT;                           -- Individual measured.
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS autoimmune_disease TEXT;                   -- Related autoimmune disease.
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS disease_stage TEXT;                        -- Disease stage at measurement.
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS tissue TEXT;                               -- Tissue context if applicable.
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS severity_score NUMERIC;                    -- Disease severity (0-10).
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS measurement_date TIMESTAMPTZ;              -- Date of phenotype assessment.
ALTER TABLE clinical_phenotypes ADD COLUMN IF NOT EXISTS has_immune_dysfunction BOOLEAN;            -- True when immune dysfunction markers elevated.
COMMENT ON TABLE clinical_phenotypes IS 'Clinical phenotypes including severity, immune dysfunction markers, and feedback from disease progression.';
COMMENT ON COLUMN clinical_phenotypes.clinical_phenotype_id IS 'Stable identifier for each phenotype measurement.';
COMMENT ON COLUMN clinical_phenotypes.phenotype_label IS 'Phenotype name.';
COMMENT ON COLUMN clinical_phenotypes.individual IS 'Individual measured.';
COMMENT ON COLUMN clinical_phenotypes.autoimmune_disease IS 'Related autoimmune disease.';
COMMENT ON COLUMN clinical_phenotypes.disease_stage IS 'Disease stage at measurement.';
COMMENT ON COLUMN clinical_phenotypes.tissue IS 'Tissue context if applicable.';
COMMENT ON COLUMN clinical_phenotypes.severity_score IS 'Disease severity (0-10).';
COMMENT ON COLUMN clinical_phenotypes.measurement_date IS 'Date of phenotype assessment.';
COMMENT ON COLUMN clinical_phenotypes.has_immune_dysfunction IS 'True when immune dysfunction markers elevated.';

-- ----------------------------------------------------------------------------
-- CausalMechanisms: Inferred causal mechanisms linking variants, exposures, and molecular state to clinical phenotypes; must be experimentally falsifiable.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS causal_mechanisms (
  causal_mechanism_id                 TEXT                 PRIMARY KEY          -- Stable identifier for each causal mechanism hypothesis.
);
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS mechanism_label TEXT;                        -- Human-readable mechanism description.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS individual TEXT;                             -- Individual for whom mechanism is inferred.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS genomic_variant TEXT;                        -- Primary genomic variant if applicable.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS environmental_exposure TEXT;                 -- Environmental exposure if gene-environment interaction.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS mechanism_type TEXT;                         -- Type: regulatory, coding, gene-environment-microbiome, epigenetic-inheritance, enhancer-promoter, feedback.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS has_pleiotropy BOOLEAN;                      -- True when mechanism shows pleiotropy across phenotypes.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS intervention_targets TEXT;                   -- Intervention targets derived from this mechanism.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS evidence_items TEXT;                         -- Evidence items supporting this mechanism.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS cohort_replications TEXT;                    -- Cross-cohort replications of this mechanism.
ALTER TABLE causal_mechanisms ADD COLUMN IF NOT EXISTS negative_control_tests TEXT;                 -- Negative-control tests on this mechanism.
COMMENT ON TABLE causal_mechanisms IS 'Inferred causal mechanisms linking variants, exposures, and molecular state to clinical phenotypes; must be experimentally falsifiable.';
COMMENT ON COLUMN causal_mechanisms.causal_mechanism_id IS 'Stable identifier for each causal mechanism hypothesis.';
COMMENT ON COLUMN causal_mechanisms.mechanism_label IS 'Human-readable mechanism description.';
COMMENT ON COLUMN causal_mechanisms.individual IS 'Individual for whom mechanism is inferred.';
COMMENT ON COLUMN causal_mechanisms.genomic_variant IS 'Primary genomic variant if applicable.';
COMMENT ON COLUMN causal_mechanisms.environmental_exposure IS 'Environmental exposure if gene-environment interaction.';
COMMENT ON COLUMN causal_mechanisms.mechanism_type IS 'Type: regulatory, coding, gene-environment-microbiome, epigenetic-inheritance, enhancer-promoter, feedback.';
COMMENT ON COLUMN causal_mechanisms.has_pleiotropy IS 'True when mechanism shows pleiotropy across phenotypes.';
COMMENT ON COLUMN causal_mechanisms.intervention_targets IS 'Intervention targets derived from this mechanism.';
COMMENT ON COLUMN causal_mechanisms.evidence_items IS 'Evidence items supporting this mechanism.';
COMMENT ON COLUMN causal_mechanisms.cohort_replications IS 'Cross-cohort replications of this mechanism.';
COMMENT ON COLUMN causal_mechanisms.negative_control_tests IS 'Negative-control tests on this mechanism.';

-- ----------------------------------------------------------------------------
-- EpistaticInteractions: Higher-order epistasis and pleiotropy interactions between genomic variants.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS epistatic_interactions (
  epistatic_interaction_id            TEXT                 PRIMARY KEY          -- Stable identifier for each epistatic interaction.
);
ALTER TABLE epistatic_interactions ADD COLUMN IF NOT EXISTS interaction_label TEXT;                 -- Human-readable interaction label.
ALTER TABLE epistatic_interactions ADD COLUMN IF NOT EXISTS individual TEXT;                        -- Individual exhibiting interaction.
ALTER TABLE epistatic_interactions ADD COLUMN IF NOT EXISTS primary_variant TEXT;                   -- First variant in interaction.
ALTER TABLE epistatic_interactions ADD COLUMN IF NOT EXISTS secondary_variant TEXT;                 -- Second variant in interaction.
ALTER TABLE epistatic_interactions ADD COLUMN IF NOT EXISTS epistasis_score NUMERIC;                -- Higher-order epistasis effect score (0-1).
ALTER TABLE epistatic_interactions ADD COLUMN IF NOT EXISTS has_pleiotropy BOOLEAN;                 -- True when interaction shows pleiotropy.
COMMENT ON TABLE epistatic_interactions IS 'Higher-order epistasis and pleiotropy interactions between genomic variants.';
COMMENT ON COLUMN epistatic_interactions.epistatic_interaction_id IS 'Stable identifier for each epistatic interaction.';
COMMENT ON COLUMN epistatic_interactions.interaction_label IS 'Human-readable interaction label.';
COMMENT ON COLUMN epistatic_interactions.individual IS 'Individual exhibiting interaction.';
COMMENT ON COLUMN epistatic_interactions.primary_variant IS 'First variant in interaction.';
COMMENT ON COLUMN epistatic_interactions.secondary_variant IS 'Second variant in interaction.';
COMMENT ON COLUMN epistatic_interactions.epistasis_score IS 'Higher-order epistasis effect score (0-1).';
COMMENT ON COLUMN epistatic_interactions.has_pleiotropy IS 'True when interaction shows pleiotropy.';

-- ----------------------------------------------------------------------------
-- CounterfactualTrajectories: Counterfactual disease trajectories inferred without randomized perturbation data.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS counterfactual_trajectories (
  counterfactual_trajectory_id        TEXT                 PRIMARY KEY          -- Stable identifier for each counterfactual trajectory.
);
ALTER TABLE counterfactual_trajectories ADD COLUMN IF NOT EXISTS trajectory_label TEXT;             -- Description of hypothetical scenario.
ALTER TABLE counterfactual_trajectories ADD COLUMN IF NOT EXISTS individual TEXT;                   -- Individual whose trajectory is modeled.
ALTER TABLE counterfactual_trajectories ADD COLUMN IF NOT EXISTS autoimmune_disease TEXT;           -- Target autoimmune disease.
ALTER TABLE counterfactual_trajectories ADD COLUMN IF NOT EXISTS projected_severity NUMERIC;        -- Projected severity under counterfactual (0-10).
ALTER TABLE counterfactual_trajectories ADD COLUMN IF NOT EXISTS horizon_months INTEGER;            -- Prediction horizon in months.
ALTER TABLE counterfactual_trajectories ADD COLUMN IF NOT EXISTS intervention_applied TEXT;         -- Hypothetical intervention (empty = no treatment).
COMMENT ON TABLE counterfactual_trajectories IS 'Counterfactual disease trajectories inferred without randomized perturbation data.';
COMMENT ON COLUMN counterfactual_trajectories.counterfactual_trajectory_id IS 'Stable identifier for each counterfactual trajectory.';
COMMENT ON COLUMN counterfactual_trajectories.trajectory_label IS 'Description of hypothetical scenario.';
COMMENT ON COLUMN counterfactual_trajectories.individual IS 'Individual whose trajectory is modeled.';
COMMENT ON COLUMN counterfactual_trajectories.autoimmune_disease IS 'Target autoimmune disease.';
COMMENT ON COLUMN counterfactual_trajectories.projected_severity IS 'Projected severity under counterfactual (0-10).';
COMMENT ON COLUMN counterfactual_trajectories.horizon_months IS 'Prediction horizon in months.';
COMMENT ON COLUMN counterfactual_trajectories.intervention_applied IS 'Hypothetical intervention (empty = no treatment).';

-- ----------------------------------------------------------------------------
-- IndividualPredictions: Predictions of disease onset, severity, treatment response, and adverse effects with calibrated uncertainty for ancestry-equitable risk prediction.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS individual_predictions (
  individual_prediction_id            TEXT                 PRIMARY KEY          -- Stable identifier for each prediction record.
);
ALTER TABLE individual_predictions ADD COLUMN IF NOT EXISTS prediction_label TEXT;                  -- Prediction type label.
ALTER TABLE individual_predictions ADD COLUMN IF NOT EXISTS individual TEXT;                        -- Individual predicted.
ALTER TABLE individual_predictions ADD COLUMN IF NOT EXISTS autoimmune_disease TEXT;                -- Target autoimmune disease.
ALTER TABLE individual_predictions ADD COLUMN IF NOT EXISTS prediction_type TEXT;                   -- Onset, Severity, TreatmentResponse, or AdverseEffect.
ALTER TABLE individual_predictions ADD COLUMN IF NOT EXISTS calibration_bins TEXT;                  -- Reliability bins for this prediction.
COMMENT ON TABLE individual_predictions IS 'Predictions of disease onset, severity, treatment response, and adverse effects with calibrated uncertainty for ancestry-equitable risk prediction.';
COMMENT ON COLUMN individual_predictions.individual_prediction_id IS 'Stable identifier for each prediction record.';
COMMENT ON COLUMN individual_predictions.prediction_label IS 'Prediction type label.';
COMMENT ON COLUMN individual_predictions.individual IS 'Individual predicted.';
COMMENT ON COLUMN individual_predictions.autoimmune_disease IS 'Target autoimmune disease.';
COMMENT ON COLUMN individual_predictions.prediction_type IS 'Onset, Severity, TreatmentResponse, or AdverseEffect.';
COMMENT ON COLUMN individual_predictions.calibration_bins IS 'Reliability bins for this prediction.';

-- ----------------------------------------------------------------------------
-- CalibrationBins: Per-prediction reliability-curve bins, seeded from the held-out coverage of this individual's own ancestry x disease. Calibration is an aggregation over these rows.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS calibration_bins (
  calibration_bin_id                  TEXT                 PRIMARY KEY          -- Stable id for this bin.
);
ALTER TABLE calibration_bins ADD COLUMN IF NOT EXISTS bin_label TEXT;                               -- Human label.
ALTER TABLE calibration_bins ADD COLUMN IF NOT EXISTS individual_prediction TEXT;                   -- FK to the prediction this bin calibrates.
ALTER TABLE calibration_bins ADD COLUMN IF NOT EXISTS predicted_probability_band NUMERIC;           -- OBSERVATION: predicted-probability midpoint of this bin (0-1).
ALTER TABLE calibration_bins ADD COLUMN IF NOT EXISTS observed_event_rate NUMERIC;                  -- OBSERVATION: empirical event rate among held-out cases in this band, matched to this individual's ancestry x disease.
ALTER TABLE calibration_bins ADD COLUMN IF NOT EXISTS coverage_count INTEGER;                       -- OBSERVATION: number of held-out outcomes in this band for this ancestry x disease.
COMMENT ON TABLE calibration_bins IS 'Per-prediction reliability-curve bins, seeded from the held-out coverage of this individual''s own ancestry x disease. Calibration is an aggregation over these rows.';
COMMENT ON COLUMN calibration_bins.calibration_bin_id IS 'Stable id for this bin.';
COMMENT ON COLUMN calibration_bins.bin_label IS 'Human label.';
COMMENT ON COLUMN calibration_bins.individual_prediction IS 'FK to the prediction this bin calibrates.';
COMMENT ON COLUMN calibration_bins.predicted_probability_band IS 'OBSERVATION: predicted-probability midpoint of this bin (0-1).';
COMMENT ON COLUMN calibration_bins.observed_event_rate IS 'OBSERVATION: empirical event rate among held-out cases in this band, matched to this individual''s ancestry x disease.';
COMMENT ON COLUMN calibration_bins.coverage_count IS 'OBSERVATION: number of held-out outcomes in this band for this ancestry x disease.';

-- ----------------------------------------------------------------------------
-- InterventionTargets: Validated intervention targets for gene-based and cell-based therapies derived from falsifiable causal mechanisms.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS intervention_targets (
  intervention_target_id              TEXT                 PRIMARY KEY          -- Stable identifier for each intervention target.
);
ALTER TABLE intervention_targets ADD COLUMN IF NOT EXISTS target_label TEXT;                        -- Target name (gene, pathway, cell type).
ALTER TABLE intervention_targets ADD COLUMN IF NOT EXISTS causal_mechanism TEXT;                    -- Parent causal mechanism.
ALTER TABLE intervention_targets ADD COLUMN IF NOT EXISTS autoimmune_disease TEXT;                  -- Target autoimmune disease.
ALTER TABLE intervention_targets ADD COLUMN IF NOT EXISTS therapy_class TEXT;                       -- Gene-based, Cell-based, or Environmental.
ALTER TABLE intervention_targets ADD COLUMN IF NOT EXISTS is_validated BOOLEAN;                     -- True when target is validated for clinical trials.
COMMENT ON TABLE intervention_targets IS 'Validated intervention targets for gene-based and cell-based therapies derived from falsifiable causal mechanisms.';
COMMENT ON COLUMN intervention_targets.intervention_target_id IS 'Stable identifier for each intervention target.';
COMMENT ON COLUMN intervention_targets.target_label IS 'Target name (gene, pathway, cell type).';
COMMENT ON COLUMN intervention_targets.causal_mechanism IS 'Parent causal mechanism.';
COMMENT ON COLUMN intervention_targets.autoimmune_disease IS 'Target autoimmune disease.';
COMMENT ON COLUMN intervention_targets.therapy_class IS 'Gene-based, Cell-based, or Environmental.';
COMMENT ON COLUMN intervention_targets.is_validated IS 'True when target is validated for clinical trials.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- AutoimmuneDiseases
CREATE INDEX IF NOT EXISTS idx_autoimmune_diseases_disease_stages ON autoimmune_diseases (disease_stages);
CREATE INDEX IF NOT EXISTS idx_autoimmune_diseases_treatments ON autoimmune_diseases (treatments);
CREATE INDEX IF NOT EXISTS idx_autoimmune_diseases_clinical_phenotypes ON autoimmune_diseases (clinical_phenotypes);
CREATE INDEX IF NOT EXISTS idx_autoimmune_diseases_individual_predictions ON autoimmune_diseases (individual_predictions);
CREATE INDEX IF NOT EXISTS idx_autoimmune_diseases_counterfactual_trajectories ON autoimmune_diseases (counterfactual_trajectories);
CREATE INDEX IF NOT EXISTS idx_autoimmune_diseases_intervention_targets ON autoimmune_diseases (intervention_targets);

-- DiseaseStages
CREATE INDEX IF NOT EXISTS idx_disease_stages_autoimmune_disease ON disease_stages (autoimmune_disease);

-- Tissues
CREATE INDEX IF NOT EXISTS idx_tissues_tissue_label ON tissues (tissue_label);
CREATE INDEX IF NOT EXISTS idx_tissues_omics_assays ON tissues (omics_assays);

-- OmicsModalities
CREATE INDEX IF NOT EXISTS idx_omics_modalities_omics_assays ON omics_modalities (omics_assays);

-- FederatedDatasets
CREATE INDEX IF NOT EXISTS idx_federated_datasets_individuals ON federated_datasets (individuals);
CREATE INDEX IF NOT EXISTS idx_federated_datasets_omics_assays ON federated_datasets (omics_assays);
CREATE INDEX IF NOT EXISTS idx_federated_datasets_cohort_replications ON federated_datasets (cohort_replications);

-- VariantTypes
CREATE INDEX IF NOT EXISTS idx_variant_types_genomic_variants ON variant_types (genomic_variants);

-- Individuals
CREATE INDEX IF NOT EXISTS idx_individuals_federated_dataset ON individuals (federated_dataset);
CREATE INDEX IF NOT EXISTS idx_individuals_genomic_variants ON individuals (genomic_variants);
CREATE INDEX IF NOT EXISTS idx_individuals_omics_assays ON individuals (omics_assays);
CREATE INDEX IF NOT EXISTS idx_individuals_environmental_exposures ON individuals (environmental_exposures);
CREATE INDEX IF NOT EXISTS idx_individuals_treatments ON individuals (treatments);
CREATE INDEX IF NOT EXISTS idx_individuals_clinical_phenotypes ON individuals (clinical_phenotypes);
CREATE INDEX IF NOT EXISTS idx_individuals_causal_mechanisms ON individuals (causal_mechanisms);
CREATE INDEX IF NOT EXISTS idx_individuals_epistatic_interactions ON individuals (epistatic_interactions);
CREATE INDEX IF NOT EXISTS idx_individuals_counterfactual_trajectories ON individuals (counterfactual_trajectories);
CREATE INDEX IF NOT EXISTS idx_individuals_individual_predictions ON individuals (individual_predictions);

-- GenomicVariants
CREATE INDEX IF NOT EXISTS idx_genomic_variants_individual ON genomic_variants (individual);
CREATE INDEX IF NOT EXISTS idx_genomic_variants_variant_type ON genomic_variants (variant_type);

-- OmicsAssays
CREATE INDEX IF NOT EXISTS idx_omics_assays_assay_label ON omics_assays (assay_label);
CREATE INDEX IF NOT EXISTS idx_omics_assays_individual ON omics_assays (individual);
CREATE INDEX IF NOT EXISTS idx_omics_assays_omics_modality ON omics_assays (omics_modality);
CREATE INDEX IF NOT EXISTS idx_omics_assays_tissue ON omics_assays (tissue);
CREATE INDEX IF NOT EXISTS idx_omics_assays_evidence_items ON omics_assays (evidence_items);

-- EvidenceItems
CREATE INDEX IF NOT EXISTS idx_evidence_items_evidence_label ON evidence_items (evidence_label);
CREATE INDEX IF NOT EXISTS idx_evidence_items_causal_mechanism ON evidence_items (causal_mechanism);
CREATE INDEX IF NOT EXISTS idx_evidence_items_omics_assay ON evidence_items (omics_assay);

-- CohortReplications
CREATE INDEX IF NOT EXISTS idx_cohort_replications_replication_label ON cohort_replications (replication_label);
CREATE INDEX IF NOT EXISTS idx_cohort_replications_causal_mechanism ON cohort_replications (causal_mechanism);
CREATE INDEX IF NOT EXISTS idx_cohort_replications_federated_dataset ON cohort_replications (federated_dataset);

-- NegativeControlTests
CREATE INDEX IF NOT EXISTS idx_negative_control_tests_control_label ON negative_control_tests (control_label);
CREATE INDEX IF NOT EXISTS idx_negative_control_tests_causal_mechanism ON negative_control_tests (causal_mechanism);

-- EnvironmentalExposures
CREATE INDEX IF NOT EXISTS idx_environmental_exposures_individual ON environmental_exposures (individual);

-- Treatments
CREATE INDEX IF NOT EXISTS idx_treatments_individual ON treatments (individual);
CREATE INDEX IF NOT EXISTS idx_treatments_autoimmune_disease ON treatments (autoimmune_disease);

-- ClinicalPhenotypes
CREATE INDEX IF NOT EXISTS idx_clinical_phenotypes_individual ON clinical_phenotypes (individual);
CREATE INDEX IF NOT EXISTS idx_clinical_phenotypes_autoimmune_disease ON clinical_phenotypes (autoimmune_disease);
CREATE INDEX IF NOT EXISTS idx_clinical_phenotypes_disease_stage ON clinical_phenotypes (disease_stage);
CREATE INDEX IF NOT EXISTS idx_clinical_phenotypes_tissue ON clinical_phenotypes (tissue);

-- CausalMechanisms
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_individual ON causal_mechanisms (individual);
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_genomic_variant ON causal_mechanisms (genomic_variant);
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_mechanism_type ON causal_mechanisms (mechanism_type);
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_intervention_targets ON causal_mechanisms (intervention_targets);
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_evidence_items ON causal_mechanisms (evidence_items);
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_cohort_replications ON causal_mechanisms (cohort_replications);
CREATE INDEX IF NOT EXISTS idx_causal_mechanisms_negative_control_tests ON causal_mechanisms (negative_control_tests);

-- EpistaticInteractions
CREATE INDEX IF NOT EXISTS idx_epistatic_interactions_individual ON epistatic_interactions (individual);
CREATE INDEX IF NOT EXISTS idx_epistatic_interactions_primary_variant ON epistatic_interactions (primary_variant);
CREATE INDEX IF NOT EXISTS idx_epistatic_interactions_secondary_variant ON epistatic_interactions (secondary_variant);

-- CounterfactualTrajectories
CREATE INDEX IF NOT EXISTS idx_counterfactual_trajectories_individual ON counterfactual_trajectories (individual);
CREATE INDEX IF NOT EXISTS idx_counterfactual_trajectories_autoimmune_disease ON counterfactual_trajectories (autoimmune_disease);

-- IndividualPredictions
CREATE INDEX IF NOT EXISTS idx_individual_predictions_prediction_label ON individual_predictions (prediction_label);
CREATE INDEX IF NOT EXISTS idx_individual_predictions_individual ON individual_predictions (individual);
CREATE INDEX IF NOT EXISTS idx_individual_predictions_autoimmune_disease ON individual_predictions (autoimmune_disease);
CREATE INDEX IF NOT EXISTS idx_individual_predictions_calibration_bins ON individual_predictions (calibration_bins);

-- CalibrationBins
CREATE INDEX IF NOT EXISTS idx_calibration_bins_bin_label ON calibration_bins (bin_label);
CREATE INDEX IF NOT EXISTS idx_calibration_bins_individual_prediction ON calibration_bins (individual_prediction);

-- InterventionTargets
CREATE INDEX IF NOT EXISTS idx_intervention_targets_causal_mechanism ON intervention_targets (causal_mechanism);
CREATE INDEX IF NOT EXISTS idx_intervention_targets_autoimmune_disease ON intervention_targets (autoimmune_disease);

-- 66 FK index(es) declared.
