-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 21
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_intervention_targets CASCADE;
DROP VIEW IF EXISTS vw_calibration_bins CASCADE;
DROP VIEW IF EXISTS vw_individual_predictions CASCADE;
DROP VIEW IF EXISTS vw_counterfactual_trajectories CASCADE;
DROP VIEW IF EXISTS vw_epistatic_interactions CASCADE;
DROP VIEW IF EXISTS vw_causal_mechanisms CASCADE;
DROP VIEW IF EXISTS vw_clinical_phenotypes CASCADE;
DROP VIEW IF EXISTS vw_treatments CASCADE;
DROP VIEW IF EXISTS vw_environmental_exposures CASCADE;
DROP VIEW IF EXISTS vw_negative_control_tests CASCADE;
DROP VIEW IF EXISTS vw_cohort_replications CASCADE;
DROP VIEW IF EXISTS vw_evidence_items CASCADE;
DROP VIEW IF EXISTS vw_omics_assays CASCADE;
DROP VIEW IF EXISTS vw_genomic_variants CASCADE;
DROP VIEW IF EXISTS vw_individuals CASCADE;
DROP VIEW IF EXISTS vw_variant_types CASCADE;
DROP VIEW IF EXISTS vw_federated_datasets CASCADE;
DROP VIEW IF EXISTS vw_omics_modalities CASCADE;
DROP VIEW IF EXISTS vw_tissues CASCADE;
DROP VIEW IF EXISTS vw_disease_stages CASCADE;
DROP VIEW IF EXISTS vw_autoimmune_diseases CASCADE;

-- ----------------------------------------------------------------------------
-- vw_autoimmune_diseases: Target heterogeneous autoimmune disease definitions tracked across development, aging, tissues, and disease stages.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_autoimmune_diseases CASCADE;
CREATE VIEW vw_autoimmune_diseases WITH (security_invoker = ON) AS
SELECT
  t.autoimmune_disease_id,                                                      -- Stable identifier for each autoimmune disease (e.g. sle, ra, t1d).
  t.disease_label,                                                              -- Human-readable disease name.
  t.is_complex_disease,                                                         -- True when the disease is a multifactorial complex disease beyond simple monogenic traits.
  calc_autoimmune_diseases_name(t.autoimmune_disease_id) AS name,               -- Display label for the autoimmune disease.
  calc_autoimmune_diseases_count_of_disease_stages(t.autoimmune_disease_id) AS count_of_disease_stages,-- Number of disease stages defined for this autoimmune disease.
  calc_autoimmune_diseases_count_of_intervention_targets(t.autoimmune_disease_id) AS count_of_intervention_targets,-- Count of validated intervention targets linked to this disease.
  t.disease_stages,                                                             -- Disease stages for this autoimmune disease.
  t.treatments,                                                                 -- Treatment histories for this disease.
  t.clinical_phenotypes,                                                        -- Clinical phenotypes observed for this disease.
  t.individual_predictions,                                                     -- Predictions of disease onset, severity, and treatment response.
  t.counterfactual_trajectories,                                                -- Counterfactual disease trajectories for this disease.
  t.intervention_targets                                                        -- Experimentally falsifiable intervention targets.
FROM autoimmune_diseases t;

-- ----------------------------------------------------------------------------
-- vw_disease_stages: Ordered disease stages capturing presymptomatic, active, remission, and treatment-refractory phases along disease progression.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_disease_stages CASCADE;
CREATE VIEW vw_disease_stages WITH (security_invoker = ON) AS
SELECT
  t.disease_stage_id,                                                           -- Stable identifier for each disease stage.
  t.stage_label,                                                                -- Human-readable stage label (e.g. presymptomatic, active).
  t.sort_order,                                                                 -- Numeric ordering of stages along disease progression.
  t.autoimmune_disease,                                                         -- Parent autoimmune disease.
  calc_disease_stages_name(t.disease_stage_id) AS name,                         -- Display label combining disease and stage.
  calc_disease_stages_autoimmune_disease_disease_label(t.disease_stage_id) AS autoimmune_disease_disease_label,-- Lookup of parent disease label.
  calc_disease_stages_is_presymptomatic(t.disease_stage_id) AS is_presymptomatic-- True when stage is presymptomatic diagnosis window.
FROM disease_stages t;

-- ----------------------------------------------------------------------------
-- vw_tissues: Anatomical tissues where omics assays resolve cell-state-specific effects; includes cases of missing tissues.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_tissues CASCADE;
CREATE VIEW vw_tissues WITH (security_invoker = ON) AS
SELECT
  t.tissue_id,                                                                  -- Stable identifier for each tissue type.
  t.tissue_label,                                                               -- Human-readable tissue name (blood, gut, synovium, skin, brain).
  calc_tissues_name(t.tissue_id) AS name,                                       -- Display label for the tissue.
  calc_tissues_count_of_omics_assays(t.tissue_id) AS count_of_omics_assays,     -- Number of omics assays performed on this tissue.
  t.omics_assays                                                                -- Omics assays performed on this tissue.
FROM tissues t;

-- ----------------------------------------------------------------------------
-- vw_omics_modalities: Registry of omics assay modalities: RNA-seq, ATAC-seq, proteomics, metabolomics, methylomes, chromatin-conformation, immune-receptor repertoires, microbiomes, and long-read genomes.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_omics_modalities CASCADE;
CREATE VIEW vw_omics_modalities WITH (security_invoker = ON) AS
SELECT
  t.omics_modality_id,                                                          -- Stable identifier for each omics modality.
  t.modality_label,                                                             -- Human-readable modality name.
  t.is_single_cell,                                                             -- True for single-cell or spatial assays resolving cellular states.
  calc_omics_modalities_name(t.omics_modality_id) AS name,                      -- Display label for the omics modality.
  calc_omics_modalities_count_of_omics_assays(t.omics_modality_id) AS count_of_omics_assays,-- Count of assays using this modality.
  t.omics_assays                                                                -- Assays of this modality.
FROM omics_modalities t;

-- ----------------------------------------------------------------------------
-- vw_federated_datasets: Privacy-preserving federated datasets contributing cohort partitions without centralizing raw genomes.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_federated_datasets CASCADE;
CREATE VIEW vw_federated_datasets WITH (security_invoker = ON) AS
SELECT
  t.federated_dataset_id,                                                       -- Stable identifier for each federated data node.
  t.node_label,                                                                 -- Human-readable federated node name.
  t.region,                                                                     -- Geographic region; shifting environments may alter exposure profiles.
  t.is_privacy_preserving,                                                      -- True when node uses privacy-preserving federated learning.
  calc_federated_datasets_name(t.federated_dataset_id) AS name,                 -- Display label for the federated dataset.
  calc_federated_datasets_count_of_individuals(t.federated_dataset_id) AS count_of_individuals,-- Individuals enrolled via this federated node.
  t.individuals,                                                                -- Individuals linked to this federated dataset.
  t.omics_assays,                                                               -- Omics assays sourced from this node.
  t.cohort_replications                                                         -- Replications run in this cohort node.
FROM federated_datasets t;

-- ----------------------------------------------------------------------------
-- vw_variant_types: Classification of genomic variant mechanisms: regulatory, coding, repeat expansions, mobile-element insertions, HLA haplotypes, structural variants, de novo mutations, somatic mosaicism, mitochondrial variation.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_variant_types CASCADE;
CREATE VIEW vw_variant_types WITH (security_invoker = ON) AS
SELECT
  t.variant_type_id,                                                            -- Stable identifier for each variant type.
  t.type_label,                                                                 -- Human-readable variant mechanism label.
  t.is_rare_variant_class,                                                      -- True when this type contributes to rare-variant burden scoring.
  calc_variant_types_name(t.variant_type_id) AS name,                           -- Display label for variant type.
  calc_variant_types_count_of_genomic_variants(t.variant_type_id) AS count_of_genomic_variants,-- Variants classified under this type.
  t.genomic_variants                                                            -- Genomic variants of this type.
FROM variant_types t;

-- ----------------------------------------------------------------------------
-- vw_individuals: Ancestrally diverse cohort participants whose phased genomes, omics profiles, exposures, and clinical phenotypes feed causal architecture inference.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_individuals CASCADE;
CREATE VIEW vw_individuals WITH (security_invoker = ON) AS
SELECT
  t.individual_id,                                                              -- Stable identifier for each individual in the million-person cohort.
  t.given_name,                                                                 -- Participant given name (de-identified mock).
  t.family_name,                                                                -- Participant family name (de-identified mock).
  t.ancestry_label,                                                             -- Ancestry label for population stratification and ancestry-equitable risk prediction.
  t.age_years,                                                                  -- Age in years spanning development and aging windows.
  t.is_ancestry_absent_from_training,                                           -- True when individual ancestry was absent from primary training data.
  t.federated_dataset,                                                          -- Federated dataset node when enrolled via privacy-preserving federation.
  t.enrollment_date,                                                            -- Longitudinal cohort enrollment date.
  t.has_cryptic_relatedness_flag,                                               -- True when cryptic relatedness or assortative mating bias detected.
  calc_individuals_name(t.individual_id) AS name,                               -- Display name for the individual.
  calc_individuals_federated_dataset_node_label(t.individual_id) AS federated_dataset_node_label,-- Lookup of federated node label.
  calc_individuals_count_of_genomic_variants(t.individual_id) AS count_of_genomic_variants,-- Total genomic variants for rare-variant burden assessment.
  calc_individuals_count_of_causal_mechanisms(t.individual_id) AS count_of_causal_mechanisms,-- Inferred causal mechanisms linked to this individual.
  calc_individuals_count_of_epistatic_interactions(t.individual_id) AS count_of_epistatic_interactions,-- Higher-order epistasis interactions involving this individual.
  calc_individuals_rare_variant_burden_score(t.individual_id) AS rare_variant_burden_score,-- 2nd-order score from rare variant count normalized by age.
  calc_individuals_causal_architecture_score(t.individual_id) AS causal_architecture_score,-- 3rd-order composite of causal mechanisms and epistasis density.
  calc_individuals_is_development_window(t.individual_id) AS is_development_window,-- True when age falls in developmental effects window (0-25).
  calc_individuals_is_aging_window(t.individual_id) AS is_aging_window,         -- True when age falls in aging window (60+).
  calc_individuals_count_confirmed_causal_nodes(t.individual_id) AS count_confirmed_causal_nodes,-- Count of this individual's confirmed causal-architecture nodes.
  calc_individuals_sum_confirmed_causal_confidence(t.individual_id) AS sum_confirmed_causal_confidence,-- Summed confidence of this individual's confirmed causal nodes (derived causal mass).
  calc_individuals_count_cross_ancestry_confirmed_nodes(t.individual_id) AS count_cross_ancestry_confirmed_nodes,-- Confirmed nodes that also showed cross-ancestry replication.
  t.genomic_variants,                                                           -- Genomic variants for this individual.
  t.omics_assays,                                                               -- Omics assays for this individual.
  t.environmental_exposures,                                                    -- Longitudinal environmental exposures.
  t.treatments,                                                                 -- Treatment histories.
  t.clinical_phenotypes,                                                        -- Clinical phenotypes.
  t.causal_mechanisms,                                                          -- Inferred causal mechanisms.
  t.epistatic_interactions,                                                     -- Epistatic interactions.
  t.counterfactual_trajectories,                                                -- Counterfactual trajectories.
  t.individual_predictions                                                      -- Individual predictions.
FROM individuals t;

-- ----------------------------------------------------------------------------
-- vw_genomic_variants: Genomic variant calls per individual spanning regulatory, coding, structural, HLA haplotypes, de novo mutations, somatic mosaicism, and mitochondrial variation.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_genomic_variants CASCADE;
CREATE VIEW vw_genomic_variants WITH (security_invoker = ON) AS
SELECT
  t.genomic_variant_id,                                                         -- Stable identifier for each genomic variant record.
  t.variant_label,                                                              -- Human-readable variant label (gene/locus).
  t.individual,                                                                 -- Individual carrying this variant.
  t.variant_type,                                                               -- Variant mechanism classification.
  t.allele_frequency,                                                           -- Population allele frequency for rare-variant burden.
  t.has_allele_specific_expression,                                             -- True when allele-specific expression observed.
  calc_genomic_variants_name(t.genomic_variant_id) AS name,                     -- Display label.
  calc_genomic_variants_variant_type_label(t.genomic_variant_id) AS variant_type_label,-- Lookup of variant type label.
  calc_genomic_variants_variant_class_is_rare(t.genomic_variant_id) AS variant_class_is_rare,-- Whether this variant's class is a rare-variant class (observed type property).
  calc_genomic_variants_individual_ancestry_label(t.genomic_variant_id) AS individual_ancestry_label,-- Lookup of individual ancestry for stratification checks.
  calc_genomic_variants_is_rare_variant(t.genomic_variant_id) AS is_rare_variant,-- True when allele frequency below 0.01.
  calc_genomic_variants_is_causal_candidate(t.genomic_variant_id) AS is_causal_candidate-- Derived: rare (by frequency or class) AND shows allele-specific expression.
FROM genomic_variants t;

-- ----------------------------------------------------------------------------
-- vw_omics_assays: Omics assay instances linking individuals to modalities and tissues; captures batch effects, measurement error, and missing tissues.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_omics_assays CASCADE;
CREATE VIEW vw_omics_assays WITH (security_invoker = ON) AS
SELECT
  t.omics_assay_id,                                                             -- Stable identifier for each omics assay.
  t.assay_label,                                                                -- Human-readable assay label.
  t.individual,                                                                 -- Individual assayed.
  t.omics_modality,                                                             -- Omics modality used.
  t.tissue,                                                                     -- Tissue sampled; empty when missing tissues.
  t.federated_dataset,                                                          -- Source federated node if applicable.
  t.batch_id,                                                                   -- Sequencing batch for batch effects control.
  t.measurement_error_score,                                                    -- Estimated measurement error (0-1).
  t.has_cell_state_specific_effect,                                             -- True when cell-state-specific effects detected.
  calc_omics_assays_name(t.omics_assay_id) AS name,                             -- Display label.
  calc_omics_assays_modality_label(t.omics_assay_id) AS modality_label,         -- Lookup of modality label.
  calc_omics_assays_tissue_label(t.omics_assay_id) AS tissue_label,             -- Lookup of tissue label.
  calc_omics_assays_has_batch_effect_risk(t.omics_assay_id) AS has_batch_effect_risk,-- True when measurement error exceeds 0.3.
  calc_omics_assays_is_high_quality_assay(t.omics_assay_id) AS is_high_quality_assay,-- 2nd-order quality flag.
  t.evidence_items                                                              -- Evidence items measured in this assay.
FROM omics_assays t;

-- ----------------------------------------------------------------------------
-- vw_evidence_items: One observed support signal for a causal mechanism, measured by one omics assay. Mechanism confidence is an aggregation over these rows.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_evidence_items CASCADE;
CREATE VIEW vw_evidence_items WITH (security_invoker = ON) AS
SELECT
  t.evidence_item_id,                                                           -- Stable id for this evidence observation.
  t.evidence_label,                                                             -- Human label for the evidence row.
  t.causal_mechanism,                                                           -- FK to the mechanism this evidence supports.
  t.omics_assay,                                                                -- FK to the omics assay this signal was measured in.
  t.effect_size,                                                                -- OBSERVATION: measured (absolute) effect magnitude.
  t.standard_error,                                                             -- OBSERVATION: measured standard error of the effect.
  t.is_cross_modality,                                                          -- OBSERVATION: TRUE if this signal comes from a different omics modality than the mechanism's primary one.
  t.is_negative_control_arm,                                                    -- OBSERVATION: TRUE if this row is a measured control arm rather than support.
  t.is_adjusted_for_ancestry_pcs,                                               -- OBSERVATION: TRUE if the analysis adjusted for ancestry principal components.
  t.is_adjusted_for_batch,                                                      -- OBSERVATION: TRUE if the analysis adjusted for batch.
  calc_evidence_items_name(t.evidence_item_id) AS name,                         -- Display name.
  calc_evidence_items_assay_is_high_quality(t.evidence_item_id) AS assay_is_high_quality,-- Whether the supporting assay passed quality control.
  calc_evidence_items_z_stat(t.evidence_item_id) AS z_stat,                     -- Derived signal-to-noise ratio (effect / SE), 0 if SE non-positive.
  calc_evidence_items_is_confound_controlled(t.evidence_item_id) AS is_confound_controlled,-- Derived: both ancestry-PC and batch adjustment present.
  calc_evidence_items_is_qualified_evidence(t.evidence_item_id) AS is_qualified_evidence-- Derived: clean assay, real support arm, signal-to-noise >= 2, confound-controlled.
FROM evidence_items t;

-- ----------------------------------------------------------------------------
-- vw_cohort_replications: One re-test of a causal mechanism in another federated cohort. Replication and cross-ancestry transport are aggregations over these rows.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_cohort_replications CASCADE;
CREATE VIEW vw_cohort_replications WITH (security_invoker = ON) AS
SELECT
  t.cohort_replication_id,                                                      -- Stable id for this replication attempt.
  t.replication_label,                                                          -- Human label.
  t.causal_mechanism,                                                           -- FK to the mechanism being re-tested.
  t.federated_dataset,                                                          -- FK to the cohort node the re-test ran in.
  t.replication_effect_sign,                                                    -- OBSERVATION: sign of the re-estimated effect (+1 / -1 / 0).
  t.replication_p_value,                                                        -- OBSERVATION: p-value of the re-test.
  t.replication_ancestry_label,                                                 -- OBSERVATION: ancestry of the cohort the re-test ran in.
  calc_cohort_replications_name(t.cohort_replication_id) AS name,               -- Display name.
  calc_cohort_replications_replicated_at_nominal_sig(t.cohort_replication_id) AS replicated_at_nominal_sig,-- Derived: reproduced the predicted (positive) sign at nominal significance.
  calc_cohort_replications_mechanism_primary_ancestry(t.cohort_replication_id) AS mechanism_primary_ancestry,-- Ancestry of the individual the mechanism was discovered in.
  calc_cohort_replications_is_different_ancestry_replication(t.cohort_replication_id) AS is_different_ancestry_replication,-- Derived: the re-test ran in a different ancestry than discovery.
  calc_cohort_replications_is_cross_ancestry_concordant(t.cohort_replication_id) AS is_cross_ancestry_concordant-- Derived: replicated at significance AND in a different ancestry (the transportability atom).
FROM cohort_replications t;

-- ----------------------------------------------------------------------------
-- vw_negative_control_tests: One stratification / permutation control on a causal mechanism. A true causal signal collapses under the control.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_negative_control_tests CASCADE;
CREATE VIEW vw_negative_control_tests WITH (security_invoker = ON) AS
SELECT
  t.negative_control_test_id,                                                   -- Stable id for this control test.
  t.control_label,                                                              -- Human label.
  t.causal_mechanism,                                                           -- FK to the mechanism being controlled.
  t.test_kind,                                                                  -- OBSERVATION: kind of control (ancestry-permutation / batch-stratified / negative-control).
  t.permutation_effect_size,                                                    -- OBSERVATION: (absolute) effect measured under the null/permuted control.
  t.null_threshold,                                                             -- OBSERVATION: pre-registered null-band half-width the control must stay within.
  calc_negative_control_tests_name(t.negative_control_test_id) AS name,         -- Display name.
  calc_negative_control_tests_is_survived(t.negative_control_test_id) AS is_survived-- Derived: signal collapses under the control (within the null band), as a true causal effect should.
FROM negative_control_tests t;

-- ----------------------------------------------------------------------------
-- vw_environmental_exposures: Longitudinal environmental exposures contributing to gene-environment-microbiome interactions and shifting environments.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_environmental_exposures CASCADE;
CREATE VIEW vw_environmental_exposures WITH (security_invoker = ON) AS
SELECT
  t.environmental_exposure_id,                                                  -- Stable identifier for each exposure record.
  t.exposure_label,                                                             -- Exposure name (smoking, UV, particulate, etc.).
  t.individual,                                                                 -- Exposed individual.
  t.exposure_level,                                                             -- Quantified exposure intensity.
  t.exposure_start_date,                                                        -- Start of longitudinal exposure window.
  t.is_maternal_effect,                                                         -- True when exposure reflects maternal developmental effects.
  calc_environmental_exposures_name(t.environmental_exposure_id) AS name,       -- Display label.
  calc_environmental_exposures_individual_ancestry_label(t.environmental_exposure_id) AS individual_ancestry_label,-- Ancestry lookup for stratification.
  calc_environmental_exposures_is_high_exposure(t.environmental_exposure_id) AS is_high_exposure-- True when exposure level exceeds threshold.
FROM environmental_exposures t;

-- ----------------------------------------------------------------------------
-- vw_treatments: Treatment histories capturing treatment-induced changes, treatment response, and adverse effects.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_treatments CASCADE;
CREATE VIEW vw_treatments WITH (security_invoker = ON) AS
SELECT
  t.treatment_id,                                                               -- Stable identifier for each treatment record.
  t.treatment_label,                                                            -- Therapy name.
  t.individual,                                                                 -- Treated individual.
  t.autoimmune_disease,                                                         -- Target autoimmune disease.
  t.treatment_response,                                                         -- Response category: Complete, Partial, None, Adverse.
  t.has_treatment_induced_change,                                               -- True when molecular state shifted due to therapy.
  t.has_adverse_effect,                                                         -- True when adverse effects observed.
  t.start_date,                                                                 -- Treatment start date.
  calc_treatments_name(t.treatment_id) AS name,                                 -- Display label.
  calc_treatments_autoimmune_disease_label(t.treatment_id) AS autoimmune_disease_label,-- Disease label lookup.
  calc_treatments_is_effective_treatment(t.treatment_id) AS is_effective_treatment-- True for Complete or Partial response without adverse effects.
FROM treatments t;

-- ----------------------------------------------------------------------------
-- vw_clinical_phenotypes: Clinical phenotypes including severity, immune dysfunction markers, and feedback from disease progression.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_clinical_phenotypes CASCADE;
CREATE VIEW vw_clinical_phenotypes WITH (security_invoker = ON) AS
SELECT
  t.clinical_phenotype_id,                                                      -- Stable identifier for each phenotype measurement.
  t.phenotype_label,                                                            -- Phenotype name.
  t.individual,                                                                 -- Individual measured.
  t.autoimmune_disease,                                                         -- Related autoimmune disease.
  t.disease_stage,                                                              -- Disease stage at measurement.
  t.tissue,                                                                     -- Tissue context if applicable.
  t.severity_score,                                                             -- Disease severity (0-10).
  t.measurement_date,                                                           -- Date of phenotype assessment.
  t.has_immune_dysfunction,                                                     -- True when immune dysfunction markers elevated.
  calc_clinical_phenotypes_name(t.clinical_phenotype_id) AS name,               -- Display label.
  calc_clinical_phenotypes_disease_stage_label(t.clinical_phenotype_id) AS disease_stage_label,-- Stage label lookup.
  calc_clinical_phenotypes_is_high_severity(t.clinical_phenotype_id) AS is_high_severity,-- True when severity exceeds 7.
  calc_clinical_phenotypes_is_presymptomatic_phenotype(t.clinical_phenotype_id) AS is_presymptomatic_phenotype-- True when stage is presymptomatic.
FROM clinical_phenotypes t;

-- ----------------------------------------------------------------------------
-- vw_causal_mechanisms: Inferred causal mechanisms linking variants, exposures, and molecular state to clinical phenotypes; must be experimentally falsifiable.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_causal_mechanisms CASCADE;
CREATE VIEW vw_causal_mechanisms WITH (security_invoker = ON) AS
SELECT
  t.causal_mechanism_id,                                                        -- Stable identifier for each causal mechanism hypothesis.
  t.mechanism_label,                                                            -- Human-readable mechanism description.
  t.individual,                                                                 -- Individual for whom mechanism is inferred.
  t.genomic_variant,                                                            -- Primary genomic variant if applicable.
  t.environmental_exposure,                                                     -- Environmental exposure if gene-environment interaction.
  t.mechanism_type,                                                             -- Type: regulatory, coding, gene-environment-microbiome, epigenetic-inheritance, enhancer-promoter, feedback.
  t.has_pleiotropy,                                                             -- True when mechanism shows pleiotropy across phenotypes.
  calc_causal_mechanisms_name(t.causal_mechanism_id) AS name,                   -- Display label.
  calc_causal_mechanisms_individual_ancestry_label(t.causal_mechanism_id) AS individual_ancestry_label,-- Ancestry lookup.
  calc_causal_mechanisms_count_qualified_evidence(t.causal_mechanism_id) AS count_qualified_evidence,-- Count of qualified evidence items supporting this mechanism.
  calc_causal_mechanisms_count_modalities_supporting(t.causal_mechanism_id) AS count_modalities_supporting,-- Count of qualified cross-modality evidence items (multi-omic corroboration).
  calc_causal_mechanisms_count_intervention_targets(t.causal_mechanism_id) AS count_intervention_targets,-- Count of perturbable intervention targets for this mechanism (falsifiability requires >=1).
  calc_causal_mechanisms_is_experimentally_falsifiable(t.causal_mechanism_id) AS is_experimentally_falsifiable,-- Derived: a measurable qualified effect exists AND a named intervention can perturb it.
  calc_causal_mechanisms_count_replications(t.causal_mechanism_id) AS count_replications,-- Total cross-cohort re-tests of this mechanism.
  calc_causal_mechanisms_count_concordant_replications(t.causal_mechanism_id) AS count_concordant_replications,-- Re-tests reproducing the predicted sign at significance.
  calc_causal_mechanisms_count_cross_ancestry_concordant(t.causal_mechanism_id) AS count_cross_ancestry_concordant,-- Concordant re-tests that ran in a DIFFERENT ancestry (the transportability measurement).
  calc_causal_mechanisms_replication_fraction(t.causal_mechanism_id) AS replication_fraction,-- Derived: fraction of re-tests that were concordant (guarded division).
  calc_causal_mechanisms_replicates_across_cohorts(t.causal_mechanism_id) AS replicates_across_cohorts,-- Derived: >=2 independent re-tests and >=2 concordant.
  calc_causal_mechanisms_count_neg_control_tests(t.causal_mechanism_id) AS count_neg_control_tests,-- Negative-control tests run on this mechanism.
  calc_causal_mechanisms_count_neg_control_survived(t.causal_mechanism_id) AS count_neg_control_survived,-- Negative-control tests the mechanism survived (collapsed under the null).
  calc_causal_mechanisms_survives_negative_controls(t.causal_mechanism_id) AS survives_negative_controls,-- Derived: at least one control run AND all of them survived.
  calc_causal_mechanisms_is_spurious_derived(t.causal_mechanism_id) AS is_spurious_derived,-- Derived: spurious unless replicated, survives controls, has >=2 modalities, and is not purely pleiotropic.
  calc_causal_mechanisms_causal_confidence(t.causal_mechanism_id) AS causal_confidence,-- Derived bounded blend of qualified-evidence count, modality breadth, replication rate, and control survival.
  calc_causal_mechanisms_variant_is_causal_candidate(t.causal_mechanism_id) AS variant_is_causal_candidate,-- Whether the linked variant is itself a derived causal candidate (empty-guarded).
  calc_causal_mechanisms_is_causal_architecture_node(t.causal_mechanism_id) AS is_causal_architecture_node,-- Derived: a confirmed causal edge - confident, falsifiable, non-spurious, and grounded in a candidate variant or a real exposure.
  calc_causal_mechanisms_is_ancestry_transportable(t.causal_mechanism_id) AS is_ancestry_transportable,-- Derived: a confirmed node whose effect replicated in >=1 different ancestry (measured invariance).
  t.intervention_targets,                                                       -- Intervention targets derived from this mechanism.
  t.evidence_items,                                                             -- Evidence items supporting this mechanism.
  t.cohort_replications,                                                        -- Cross-cohort replications of this mechanism.
  t.negative_control_tests                                                      -- Negative-control tests on this mechanism.
FROM causal_mechanisms t;

-- ----------------------------------------------------------------------------
-- vw_epistatic_interactions: Higher-order epistasis and pleiotropy interactions between genomic variants.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_epistatic_interactions CASCADE;
CREATE VIEW vw_epistatic_interactions WITH (security_invoker = ON) AS
SELECT
  t.epistatic_interaction_id,                                                   -- Stable identifier for each epistatic interaction.
  t.interaction_label,                                                          -- Human-readable interaction label.
  t.individual,                                                                 -- Individual exhibiting interaction.
  t.primary_variant,                                                            -- First variant in interaction.
  t.secondary_variant,                                                          -- Second variant in interaction.
  t.epistasis_score,                                                            -- Higher-order epistasis effect score (0-1).
  t.has_pleiotropy,                                                             -- True when interaction shows pleiotropy.
  calc_epistatic_interactions_name(t.epistatic_interaction_id) AS name,         -- Display label.
  calc_epistatic_interactions_is_high_order_epistasis(t.epistatic_interaction_id) AS is_high_order_epistasis-- True when epistasis score exceeds 0.5.
FROM epistatic_interactions t;

-- ----------------------------------------------------------------------------
-- vw_counterfactual_trajectories: Counterfactual disease trajectories inferred without randomized perturbation data.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_counterfactual_trajectories CASCADE;
CREATE VIEW vw_counterfactual_trajectories WITH (security_invoker = ON) AS
SELECT
  t.counterfactual_trajectory_id,                                               -- Stable identifier for each counterfactual trajectory.
  t.trajectory_label,                                                           -- Description of hypothetical scenario.
  t.individual,                                                                 -- Individual whose trajectory is modeled.
  t.autoimmune_disease,                                                         -- Target autoimmune disease.
  t.projected_severity,                                                         -- Projected severity under counterfactual (0-10).
  t.horizon_months,                                                             -- Prediction horizon in months.
  t.intervention_applied,                                                       -- Hypothetical intervention (empty = no treatment).
  calc_counterfactual_trajectories_name(t.counterfactual_trajectory_id) AS name,-- Display label.
  calc_counterfactual_trajectories_autoimmune_disease_label(t.counterfactual_trajectory_id) AS autoimmune_disease_label,-- Disease label lookup.
  calc_counterfactual_trajectories_is_worsening_trajectory(t.counterfactual_trajectory_id) AS is_worsening_trajectory-- True when projected severity exceeds 7.
FROM counterfactual_trajectories t;

-- ----------------------------------------------------------------------------
-- vw_individual_predictions: Predictions of disease onset, severity, treatment response, and adverse effects with calibrated uncertainty for ancestry-equitable risk prediction.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_individual_predictions CASCADE;
CREATE VIEW vw_individual_predictions WITH (security_invoker = ON) AS
SELECT
  t.individual_prediction_id,                                                   -- Stable identifier for each prediction record.
  t.prediction_label,                                                           -- Prediction type label.
  t.individual,                                                                 -- Individual predicted.
  t.autoimmune_disease,                                                         -- Target autoimmune disease.
  t.prediction_type,                                                            -- Onset, Severity, TreatmentResponse, or AdverseEffect.
  calc_individual_predictions_name(t.individual_prediction_id) AS name,         -- Display label.
  calc_individual_predictions_individual_ancestry_label(t.individual_prediction_id) AS individual_ancestry_label,-- Ancestry for equity audit.
  calc_individual_predictions_is_ancestry_holdout(t.individual_prediction_id) AS is_ancestry_holdout,-- True when individual ancestry absent from training.
  calc_individual_predictions_individual_causal_mass(t.individual_prediction_id) AS individual_causal_mass,-- Summed confirmed causal confidence for this individual (empty-guarded).
  calc_individual_predictions_individual_confirmed_node_count(t.individual_prediction_id) AS individual_confirmed_node_count,-- Count of this individual's confirmed causal nodes (empty-guarded).
  calc_individual_predictions_individual_cross_ancestry_node_coun(t.individual_prediction_id) AS individual_cross_ancestry_node_count,-- Count of this individual's cross-ancestry-replicated confirmed nodes (empty-guarded).
  calc_individual_predictions_individual_has_cryptic_relatedness(t.individual_prediction_id) AS individual_has_cryptic_relatedness,-- Whether this individual carries a cryptic-relatedness leakage flag (empty-guarded).
  calc_individual_predictions_predicted_value(t.individual_prediction_id) AS predicted_value,-- Derived risk magnitude (0-10), a monotone function of validated causal mass only - rides mechanism, not ancestry correlation.
  calc_individual_predictions_count_bins(t.individual_prediction_id) AS count_bins,-- Total reliability bins for this prediction.
  calc_individual_predictions_count_well_calibrated_bins(t.individual_prediction_id) AS count_well_calibrated_bins,-- Bins passing coverage and accuracy.
  calc_individual_predictions_sum_bin_abs_error(t.individual_prediction_id) AS sum_bin_abs_error,-- Summed reliability gap across this prediction's bins.
  calc_individual_predictions_mean_bin_abs_error(t.individual_prediction_id) AS mean_bin_abs_error,-- Derived mean reliability gap; defaults to 1 (worst) when no bins exist.
  calc_individual_predictions_well_calibrated_fraction(t.individual_prediction_id) AS well_calibrated_fraction,-- Derived fraction of trustworthy bins (guarded division).
  calc_individual_predictions_calibrated_uncertainty(t.individual_prediction_id) AS calibrated_uncertainty,-- Derived reliability (HIGH = trustworthy): (1 - mean gap) scaled by well-covered-bin fraction; 0 for uncovered predictions.
  calc_individual_predictions_rests_on_confirmed_mechanism(t.individual_prediction_id) AS rests_on_confirmed_mechanism,-- Derived: grounded in >=1 validated mechanism.
  calc_individual_predictions_has_spurious_correlation_flag(t.individual_prediction_id) AS has_spurious_correlation_flag,-- Derived: spurious if no validated mechanism OR cryptic-relatedness leakage.
  calc_individual_predictions_is_falsifiability_backed(t.individual_prediction_id) AS is_falsifiability_backed,-- Derived: inherits falsifiability - every confirmed node required IsExperimentallyFalsifiable.
  calc_individual_predictions_is_transportable_to_absent_ancestry(t.individual_prediction_id) AS is_transportable_to_absent_ancestry,-- Derived: a holdout individual is transportable only with >=1 cross-ancestry-replicated node and no spurious flag.
  calc_individual_predictions_is_ancestry_transport_safe(t.individual_prediction_id) AS is_ancestry_transport_safe,-- Derived: holdout requires measured transport; in-training is vacuously safe.
  calc_individual_predictions_is_high_confidence_prediction(t.individual_prediction_id) AS is_high_confidence_prediction,-- Derived: calibrated AND not spurious.
  calc_individual_predictions_patient_stratification_tier(t.individual_prediction_id) AS patient_stratification_tier,-- Derived risk tier from the derived PredictedValue.
  calc_individual_predictions_is_clinically_actionable(t.individual_prediction_id) AS is_clinically_actionable,-- KEYSTONE: TRUE only when the prediction is high-confidence (calibrated + not spurious), falsifiability-backed, ancestry-transport-safe, and rests on a non-null derived magnitude.
  t.calibration_bins                                                            -- Reliability bins for this prediction.
FROM individual_predictions t;

-- ----------------------------------------------------------------------------
-- vw_calibration_bins: Per-prediction reliability-curve bins, seeded from the held-out coverage of this individual's own ancestry x disease. Calibration is an aggregation over these rows.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_calibration_bins CASCADE;
CREATE VIEW vw_calibration_bins WITH (security_invoker = ON) AS
SELECT
  t.calibration_bin_id,                                                         -- Stable id for this bin.
  t.bin_label,                                                                  -- Human label.
  t.individual_prediction,                                                      -- FK to the prediction this bin calibrates.
  t.predicted_probability_band,                                                 -- OBSERVATION: predicted-probability midpoint of this bin (0-1).
  t.observed_event_rate,                                                        -- OBSERVATION: empirical event rate among held-out cases in this band, matched to this individual's ancestry x disease.
  t.coverage_count,                                                             -- OBSERVATION: number of held-out outcomes in this band for this ancestry x disease.
  calc_calibration_bins_name(t.calibration_bin_id) AS name,                     -- Display name.
  calc_calibration_bins_bin_abs_error(t.calibration_bin_id) AS bin_abs_error,   -- Derived: absolute gap between predicted band and observed rate.
  calc_calibration_bins_is_well_calibrated_bin(t.calibration_bin_id) AS is_well_calibrated_bin-- Derived: enough held-out coverage AND small reliability gap.
FROM calibration_bins t;

-- ----------------------------------------------------------------------------
-- vw_intervention_targets: Validated intervention targets for gene-based and cell-based therapies derived from falsifiable causal mechanisms.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_intervention_targets CASCADE;
CREATE VIEW vw_intervention_targets WITH (security_invoker = ON) AS
SELECT
  t.intervention_target_id,                                                     -- Stable identifier for each intervention target.
  t.target_label,                                                               -- Target name (gene, pathway, cell type).
  t.causal_mechanism,                                                           -- Parent causal mechanism.
  t.autoimmune_disease,                                                         -- Target autoimmune disease.
  t.therapy_class,                                                              -- Gene-based, Cell-based, or Environmental.
  t.is_validated,                                                               -- True when target is validated for clinical trials.
  calc_intervention_targets_name(t.intervention_target_id) AS name,             -- Display label.
  calc_intervention_targets_causal_mechanism_label(t.intervention_target_id) AS causal_mechanism_label,-- Mechanism label lookup.
  calc_intervention_targets_is_gene_based_therapy(t.intervention_target_id) AS is_gene_based_therapy,-- True when therapy class is gene-based.
  calc_intervention_targets_is_cell_based_therapy(t.intervention_target_id) AS is_cell_based_therapy-- True when therapy class is cell-based.
FROM intervention_targets t;

