-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE autoimmune_diseases ENABLE ROW LEVEL SECURITY;
ALTER TABLE disease_stages ENABLE ROW LEVEL SECURITY;
ALTER TABLE tissues ENABLE ROW LEVEL SECURITY;
ALTER TABLE omics_modalities ENABLE ROW LEVEL SECURITY;
ALTER TABLE federated_datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE variant_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE individuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE genomic_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE omics_assays ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE cohort_replications ENABLE ROW LEVEL SECURITY;
ALTER TABLE negative_control_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE environmental_exposures ENABLE ROW LEVEL SECURITY;
ALTER TABLE treatments ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical_phenotypes ENABLE ROW LEVEL SECURITY;
ALTER TABLE causal_mechanisms ENABLE ROW LEVEL SECURITY;
ALTER TABLE epistatic_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE counterfactual_trajectories ENABLE ROW LEVEL SECURITY;
ALTER TABLE individual_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE calibration_bins ENABLE ROW LEVEL SECURITY;
ALTER TABLE intervention_targets ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

