#!/usr/bin/env bash
# ============================================================================
# causal_autoimmune - Database Initialization Script
# ============================================================================
# Generated by rulebook-to-postgres tool.
#
# Two responsibilities: install magic-links auth, then run all
# NN[b]?-*.sql files in lex order. Skips *.sql.disabled.
#
# THIS IS THE DEV LOOP (per plan 04). Re-running against a populated
# DB should be safe — every file is meant to be idempotent. If it
# isn't, fix the file, not this script.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CONN="postgresql://postgres@localhost:5432/causal_autoimmune"
DATABASE_URL="${DATABASE_URL:-${1:-$DEFAULT_CONN}}"

# ----------------------------------------------------------------------
# Plan 04 §8: bases-URL refusal (defense in depth).
# bases.effortlessapi.com is migration-only. Any rebuild against it
# would drop tables and lose data. Use postgres/apply-migration.sh
# instead. This check has no escape hatch by design.
# ----------------------------------------------------------------------
if echo "$DATABASE_URL" | grep -qi 'bases\.effortlessapi\.com' ; then
    echo "refusing to run init-db.sh against bases." >&2
    echo "bases is migration-only — see CLAUDE.md \"Bases is migration-only\"" >&2
    echo "use postgres/apply-migration.sh postgres/migrations/NNNN-….sql" >&2
    exit 2
fi
if [ -n "${BASES_DATABASE_URL:-}" ] && [ "$DATABASE_URL" = "$BASES_DATABASE_URL" ]; then
    echo "refusing to run init-db.sh: DATABASE_URL == BASES_DATABASE_URL" >&2
    echo "bases is migration-only — use postgres/apply-migration.sh" >&2
    exit 2
fi

echo "[init-db] target: $DATABASE_URL"

# ----------------------------------------------------------------------
# 1. Always (re-)install magic-links auth. Idempotent → safe to repeat.
# ----------------------------------------------------------------------
if [ -f "${SCRIPT_DIR}/install-magic-links.sql" ]; then
    echo "[init-db] [RUN]  install-magic-links.sql"
    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "${SCRIPT_DIR}/install-magic-links.sql"
else
    echo "[init-db] note: install-magic-links.sql not present — skipping auth install"
    echo "[init-db]       fetch from https://magiclink.effortlessapi.com/install-magic-links/v1.sql"
fi

# ----------------------------------------------------------------------
# 2. Run all NN[b]?-*.sql files in lex order. Skip *.sql.disabled.
# ----------------------------------------------------------------------
shopt -s nullglob
FILES_RUN=()
FILES_SKIP=()
for f in "${SCRIPT_DIR}"/[0-9][0-9]*-*.sql "${SCRIPT_DIR}"/[0-9][0-9]*-*.sql.disabled; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    if [[ "$base" == *.disabled ]]; then
        echo "[init-db] [SKIP] $base"
        FILES_SKIP+=("$base")
        continue
    fi
    # 99-fk-constraints.sql — FK enforcement is opt-in. Demos must never
    # fail on FK violations; the rulebook still documents the relationships
    # and 01-drop-and-create-tables.sql installs the FK indexes inline.
    if [[ "$base" == "99-fk-constraints.sql" && "${EFFORTLESS_ENFORCE_FKS:-false}" != "true" ]]; then
        echo "[init-db] [SKIP] $base (set EFFORTLESS_ENFORCE_FKS=true to apply FK constraints)"
        FILES_SKIP+=("$base")
        continue
    fi
    echo "[init-db] [RUN]  $base"
    if [[ "$base" == *b-* ]]; then
        # customize files (NNb-*) tolerate per-row errors
        psql "$DATABASE_URL" -f "$f"
    elif [[ "$base" == "05-insert-data.sql" ]]; then
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    else
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    fi
    FILES_RUN+=("$base")
done

# ----------------------------------------------------------------------
# 3. function-overrides/*.sql (per-function tweaks; errors non-fatal).
#    Two-pass: non-policy files first, then policy__* files (policies
#    often reference custom functions).
# ----------------------------------------------------------------------
run_override() {
    local sql_file="$1"
    local base; base=$(basename "$sql_file")
    if [[ "$base" == *.disabled ]]; then
        echo "[init-db] [SKIP] function-overrides/$base"
        return 0
    fi
    echo "[init-db] [RUN]  function-overrides/$base"
    psql "$DATABASE_URL" -f "$sql_file" || echo "[init-db] [WARN] $base failed (non-fatal)"
}
if compgen -G "${SCRIPT_DIR}/function-overrides/*.sql" > /dev/null 2>&1; then
    for sql_file in "${SCRIPT_DIR}/function-overrides/"*.sql; do
        base=$(basename "$sql_file")
        [[ "$base" == policy__* ]] && continue
        run_override "$sql_file"
    done
    for sql_file in "${SCRIPT_DIR}/function-overrides/"policy__*.sql; do
        [[ -f "$sql_file" ]] || continue
        run_override "$sql_file"
    done
fi

# ----------------------------------------------------------------------
# 4. Plan 04 §9: write postgres/.applied-manifest.json so tooling can
#    compare to .build-manifest.json and detect drift.
# ----------------------------------------------------------------------
APPLIED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
MANIFEST="${SCRIPT_DIR}/.applied-manifest.json"
{
    printf '{\n'
    printf '  "applied_at": "%s",\n' "$APPLIED_AT"
    printf '  "target": "%s",\n' "$DATABASE_URL"
    printf '  "files_run": ['
    sep=''
    for f in "${FILES_RUN[@]:-}"; do
        [ -z "$f" ] && continue
        printf '%s"%s"' "$sep" "$f"
        sep=','
    done
    printf '],\n'
    printf '  "files_skipped": ['
    sep=''
    for f in "${FILES_SKIP[@]:-}"; do
        [ -z "$f" ] && continue
        printf '%s"%s"' "$sep" "$f"
        sep=','
    done
    printf ']\n'
    printf '}\n'
} > "$MANIFEST"

echo "[init-db] complete (manifest: .applied-manifest.json)"

# ----------------------------------------------------------------------
# 5. REVERSE-SYNC (DB -> rulebook), the input spoke that closes the loop.
#    We only reach this line if every step above succeeded (set -euo pipefail
#    aborts before here on any failure), so the DB is fully seeded and the
#    vw_* views are computed. Snapshot every view's RAW + COMPUTED values back
#    into effortless-rulebook.json so the hub is snapshot-consistent on disk.
#
#    Mode is UPSERT (conservative): existing rows are updated in place, rows
#    only in the DB are added, rows only in the rulebook are LEFT ALONE. So
#    even if this step fails, worst case the rulebook keeps exactly the data it
#    already had — nothing is ever removed here. (The admin "Save to rulebook"
#    button offers an explicit full-overwrite/replace mode; init-db never does.)
#
#    Opt out with SNAPSHOT_RULEBOOK=false (e.g. a pure reseed where you don't
#    want the rulebook touched).
# ----------------------------------------------------------------------
if [ "${SNAPSHOT_RULEBOOK:-true}" = "true" ]; then
    SNAP="${SCRIPT_DIR}/snapshot-to-rulebook.mjs"
    if [ -f "$SNAP" ]; then
        echo "[init-db] [RUN]  snapshot-to-rulebook.mjs (DB -> rulebook, upsert)"
        # Non-fatal: a snapshot failure must not fail the build; the seeded DB
        # and the existing rulebook both remain valid.
        if DATABASE_URL="$DATABASE_URL" node "$SNAP" >/dev/null; then
            echo "[init-db] rulebook snapshot-consistent with DB (raw + computed values written back)"
        else
            echo "[init-db] [WARN] snapshot-to-rulebook failed (non-fatal); rulebook left as-is" >&2
        fi
    else
        echo "[init-db] note: snapshot-to-rulebook.mjs not present — skipping DB -> rulebook reverse-sync"
    fi
else
    echo "[init-db] SNAPSHOT_RULEBOOK=false — skipping DB -> rulebook reverse-sync"
fi
